name: 'Dagger for GitHub'
description: 'GitHub Action for Dagger, a programmable deployment system'
author: 'dagger'
branding:
  color: 'green'
  icon: 'package'

inputs:
  version:
    description: 'Dagger version'
    default: 'latest'
    required: false
  args:
    description: 'Arguments to pass to Dagger'
    required: false
  workdir:
    description: 'Working directory (below repository root)'
    default: '.'
    required: false
  install-only:
    description: 'Just install Dagger'
    default: 'false'
    required: false
  cleanup:
    description: 'Cleanup Dagger home folder at the end of a job'
    default: 'true'
    required: false
  project-update:
    description: 'Run project update before args'
    default: 'false'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/index.js'
